USE fresh_world_system;

INSERT INTO customers
(
  customer_code,
  customer_type,
  customer_name,
  contact_person,
  phone,
  whatsapp_number,
  email,
  address,
  city,
  location_island,
  airline_preference,
  incoterm,
  cold_chain_required,
  status,
  created_by
)
VALUES
(
  'FW-CLT-G001',
  'global',
  'Four Seasons — Kuda Huraa',
  'Chef Antoine',
  '+960 700 1111',
  '+960 700 1111',
  'chef@fourseasons.mv',
  'Coordinate with destination delivery agent before cargo arrival.',
  'Maldives',
  'North Malé Atoll',
  'UL',
  'CIF',
  0,
  'active',
  NULL
),
(
  'FW-CLT-G002',
  'global',
  'Hilton Maldives — Amingiri',
  'Chef Marco',
  '+960 700 2222',
  '+960 700 2222',
  'chef@hilton.mv',
  'Use standard export labels and notify resort purchasing team on AWB issue.',
  'Maldives',
  'North Malé Atoll',
  'UL',
  'CIF',
  0,
  'active',
  NULL
),
(
  'FW-CLT-G003',
  'global',
  'Waldorf Astoria — Ithaafushi',
  'Chef Pierre',
  '+960 700 3333',
  '+960 700 3333',
  'chef@waldorf.mv',
  'Cold chain required for all leafy and cut produce lines.',
  'Maldives',
  'South Malé Atoll',
  'Q2',
  'DAP',
  1,
  'active',
  NULL
),
(
  'FW-CLT-G004',
  'global',
  'Conrad Maldives — Rangali',
  'Chef James',
  '+960 700 4444',
  '+960 700 4444',
  'chef@conrad.mv',
  'Thermocol box packing required for chilled lines.',
  'Maldives',
  'Ari Atoll',
  'Q2',
  'CIF',
  1,
  'active',
  NULL
)
ON DUPLICATE KEY UPDATE
  customer_name = VALUES(customer_name),
  contact_person = VALUES(contact_person),
  phone = VALUES(phone),
  whatsapp_number = VALUES(whatsapp_number),
  email = VALUES(email),
  address = VALUES(address),
  city = VALUES(city),
  location_island = VALUES(location_island),
  airline_preference = VALUES(airline_preference),
  incoterm = VALUES(incoterm),
  cold_chain_required = VALUES(cold_chain_required),
  status = VALUES(status);